# Generated by Django 3.2.22 on 2024-03-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assign_work_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='hr_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='work_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plan', models.FileField(upload_to='')),
                ('client', models.CharField(max_length=50)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.hr_table')),
            ],
        ),
        migrations.CreateModel(
            name='ta_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_latitude', models.FloatField(null=True)),
                ('from_longitude', models.FloatField(null=True)),
                ('to_latitude', models.FloatField(null=True)),
                ('to_longitude', models.FloatField(null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.staff_table')),
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_latitude', models.FloatField()),
                ('login_longitude', models.FloatField()),
                ('distance', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('assignwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.assign_work_table')),
            ],
        ),
        migrations.CreateModel(
            name='salary_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.staff_table')),
            ],
        ),
        migrations.CreateModel(
            name='location_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='leave_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('from_date', models.DateField()),
                ('status', models.CharField(max_length=500)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.staff_table')),
            ],
        ),
        migrations.AddField(
            model_name='hr_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.login_table'),
        ),
        migrations.CreateModel(
            name='da_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('bill', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.assign_work_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.staff_table')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.FileField(upload_to='')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.staff_table')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.work_table')),
            ],
        ),
        migrations.AddField(
            model_name='assign_work_table',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.staff_table'),
        ),
        migrations.AddField(
            model_name='assign_work_table',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.work_table'),
        ),
    ]
