# Generated by Django 3.2.24 on 2024-03-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_leave_table_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.assign_work_table'),
        ),
    ]
