# Generated by Django 3.2.24 on 2024-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_attendance_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
